from pydantic import BaseModel, Field
from typing import List, Optional, Any

class Message(BaseModel):
    role: str = Field(..., description="Role of the message author: 'user' or 'assistant'")
    content: str = Field(..., description="Text content of the message")

class ChatRequest(BaseModel):
    message: str = Field(..., description="User question or input prompt")
    history: Optional[List[Message]] = Field(default=[], description="Previous conversation turn history")

class ChatResponse(BaseModel):
    agent_used: str = Field(..., description="Identifier of the specialized agent that answered")
    question: str = Field(..., description="Echoed user question")
    answer: str = Field(..., description="Clinical educational answer generated by the agent")

class WebSocketInboundMessage(BaseModel):
    type: Optional[str] = None
    message: Optional[str] = None
    history: Optional[List[dict]] = None
    image: Optional[str] = None
    data: Optional[str] = None
    text: Optional[str] = None
